[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "django-s3-file-field"
description = "A Django library for uploading files directly to AWS S3 or MinIO Storage from HTTP clients."
readme = "README.md"
requires-python = ">=3.12"
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE"]
maintainers = [{ name = "Kitware, Inc.", email = "kitware@kitware.com" }]
keywords = [
  "django",
  "django-widget",
  "resonant",
  "kitware-resonant",
  "minio",
  "s3",
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Web Environment",
  "Framework :: Django :: 5",
  "Framework :: Django :: 5.2",
  "Framework :: Django :: 6",
  "Framework :: Django :: 6.0",
  "Framework :: Django :: 6.1",
  "Framework :: Django",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python",
]
dependencies = [
  "django>=5.2",
  "djangorestframework",
]
dynamic = ["version"]

[project.urls]
Repository = "https://github.com/kitware-resonant/django-s3-file-field"
"Bug Reports" = "https://github.com/kitware-resonant/django-s3-file-field/issues"

[project.entry-points.pytest11]
s3_file_field = "s3_file_field.fixtures"

[project.optional-dependencies]
s3 = [
  # 1.14 has some breaking renames which are adopted here
  "django-storages[s3]>=1.14",
  "boto3",
]
minio = [
  # 0.5.9 pins "minio<7.2.19", which excludes the breaking API changes in minio 7.2.19
  "django-minio-storage>=0.5.9",
  # 7.2.18 is the first version to ship with inline type annotations
  "minio>=7.2.18",
]
pytest = [
  # The "fixtures.py" module (containing the "pytest" requirement) is only loaded
  # automatically via entry point by consumers who already have "pytest" installed, so
  # "pytest" isn't actually a hard requirement.
  "pytest",
]

[dependency-groups]
dev = [
  "django==6.1",
  "django-browser-reload==1.21.0",
  "django-debug-toolbar==7.1.1",
  "django-extensions==4.1",
  "django-stubs-ext==6.1.0",
  "ipython==9.16.1",
  "tox==4.60.0",
  "tox-uv==1.36.0",
  "watchdog==6.0.0",
  "werkzeug==3.1.8",
]
lint = [
  "ruff==0.16.4",
]
type = [
  "mypy==2.3.1",
  "boto3-stubs[s3]==1.43.79",
  "django-stubs[compatible-mypy]==6.1.0",
  "djangorestframework-stubs==3.18.0",
  "types-factory-boy==0.4.1",
]
test = [
  "django-stubs-ext==6.1.0",
  "factory-boy==3.3.3",
  "pytest==9.1.1",
  "pytest-cov==7.1.0",
  "pytest-django==4.14.0",
  "pytest-mock==3.15.1",
  "requests==2.34.2",
]

[tool.hatch.build]
only-include = [
  "s3_file_field",
]
artifacts = [
  "s3_file_field/static",
]

[tool.hatch.build.targets.sdist]
only-include = [
  "s3_file_field",
  # The builder needs to run again when installing the sdist, although it will no-op
  "multi_npm_builder.py",
]

[tool.hatch.build.hooks.jupyter-builder]
dependencies = ["hatch-jupyter-builder"]
build-function = "multi_npm_builder.multi_npm_builder"
ensured-targets = [
  "s3_file_field/static/s3_file_field/widget.js",
  "s3_file_field/static/s3_file_field/widget.css",
]

[[tool.hatch.build.hooks.jupyter-builder.build-kwargs.projects]]
build_cmd = "build"
path = "javascript-client"
source_dir = "javascript-client"
build_dir = "javascript-client/dist"

[[tool.hatch.build.hooks.jupyter-builder.build-kwargs.projects]]
build_cmd = "build"
path = "widget"
source_dir = "widget"
build_dir = "s3_file_field/static/s3_file_field"

[tool.hatch.version]
source = "vcs"

[tool.uv.workspace]
members = ["python-client"]

[tool.ruff]
line-length = 100
src = [".", "tests", "python-client"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  # Incompatible with formatter
  # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
  "COM812", # missing-trailing-comma
  "COM819", # prohibited-trailing-comma
  "D206", # docstring-tab-indentation
  "D300", # triple-single-quotes
  "E111", # indentation-with-invalid-multiple
  "E114", # indentation-with-invalid-multiple-comment
  "E117", # over-indented
  "ISC001", # single-line-implicit-string-concatenation
  "ISC002", # multi-line-implicit-string-concatenation
  "Q", # flake8-quotes
  "W191", # tab-indentation

  # Incompatible with Django
  "A003", # builtin-attribute-shadowing
  "ARG001", # unused-function-argument
  "ARG002", # unused-method-argument
  "RUF012", # mutable-class-default

  # Overly burdensome
  "ANN", # flake8-annotations
  "CPY001", # missing-copyright-notice
  "D1", # undocumented-*
  "EM", # flake8-errmsg
  "ERA001", # commented-out-code
  "FIX", # flake8-fixme
  "RET505", # superfluous-else-return
  "RET506", # superfluous-else-raise
  "RET507", # superfluous-else-continue
  "RET508", # superfluous-else-break
  "TD002", # missing-todo-author
  "TD003", # missing-todo-link
  "TRY003", # raise-vanilla-args

  # Project-specific
]

[tool.ruff.lint.per-file-ignores]
"dev/**" = [
  "INP001", # implicit-namespace-package
]
"**/migrations/**" = [
  "N806", # non-lowercase-variable-in-function
  "RUF012", # mutable-class-default
]
"**/settings.py" = [
  "S105", # hardcoded-password-string
]
"**/tests/**" = [
  "DJ007", # django-all-with-model-form
  "DJ008", # django-model-without-dunder-str
  "INP001", # implicit-namespace-package
  "PLR0913", # too-many-arguments
  "PLR2004", # magic-value-comparison
  "S", # flake8-bandit
  "SLF001", # private-member-access
]

[tool.ruff.lint.flake8-boolean-trap]
extend-allowed-calls = ["pydantic.Field", "django.db.models.Value"]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["ninja.Query"]

[tool.ruff.lint.flake8-self]
extend-ignore-names = ["_base_manager", "_default_manager",  "_meta"]

[tool.ruff.lint.flake8-type-checking]
runtime-evaluated-base-classes = ["pydantic.BaseModel"]
runtime-evaluated-decorators = ["pydantic.validate_call"]

[tool.ruff.lint.isort]
# Sort by name, don't cluster "from" vs "import"
force-sort-within-sections = true
# Deferred annotations allows TC* rules to move more imports into TYPE_CHECKING blocks
required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.mypy]
files = [
  "s3_file_field",
  "dev",
  "tests",
  "python-client/s3_file_field_client",
]
check_untyped_defs = true
show_error_codes = true
strict = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
plugins = [
  "mypy_django_plugin.main",
  "mypy_drf_plugin.main",
]
mypy_path = [
  # Use the same pythonpath for MyPy as for Pytest
  "tests",
]

[[tool.mypy.overrides]]
module = [
  "debug_toolbar.*",
  "storages.backends.s3",
]
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "test_app.settings"

[tool.pytest.ini_options]
testpaths = ["tests"]
# Allow test utility modules to be imported without adding the root directory to the pythonpath,
# which would cause the local "s3_file_field" module to shadow the install.
pythonpath = ["tests"]
# Configure pythonpath ourselves, not based on manage.py
django_find_project = false
addopts = [
  # Use the Pytest-recommended "importlib" mode
  "--import-mode=importlib",
  "--strict-config",
  "--strict-markers",
  "--showlocals",
  "--verbose",
  # Disable the entry point loading of "s3_file_field" fixtures, to support coverage.
  # See the comment with "pytest_plugins" in "conftest.py" for full details.
  "-p", "no:s3_file_field",
  "--cov",
  # Specifying as "--ds" will override any value in the environment
  "--ds=test_app.settings",
]
filterwarnings = [
  "error",
  # pytest often causes unclosed socket warnings
  'ignore:unclosed <socket\.socket:ResourceWarning',
]

[tool.coverage.run]
source_pkgs = [
  "s3_file_field",
]

[tool.coverage.paths]
source = [
  "s3_file_field/",
  ".tox/**/site-packages/s3_file_field/",
]
