[tox]
requires =
    tox-uv
env_list =
    lint
    type
    test-django{52,60,61}

[testenv]
runner = uv-venv-lock-runner
# Building a wheel is required to make Hatchling build hooks run
package = wheel
extras =
    s3
    minio
    pytest

[testenv:lint]
package = skip
dependency_groups =
    lint
commands =
    ruff check
    ruff format --check

[testenv:format]
package = skip
dependency_groups =
    lint
commands =
    ruff check --fix-only
    ruff format

[testenv:type]
dependency_groups =
    type
    test
commands =
    mypy {posargs}

[testenv:test-django{52,60,61}]
pass_env =
    MINIO_STORAGE_ENDPOINT
    MINIO_STORAGE_ACCESS_KEY
    MINIO_STORAGE_SECRET_KEY
    MINIO_STORAGE_MEDIA_BUCKET_NAME
dependency_groups =
    test
deps =
    django52: Django==5.2.*
    django60: Django==6.0.*
    django61: Django==6.1.*
commands =
    pytest {posargs}
