[tox]
requires =
    tox-uv
env_list =
    lint
    type
    test-django{42,51,52}

[testenv]
runner = uv-venv-lock-runner
# Building a wheel is required to make Hatchling build hooks run
package = wheel
extras =
    s3
    minio
    pytest

[testenv:lint]
package = skip
dependency_groups =
    lint
commands =
    ruff check
    ruff format --check

[testenv:format]
package = skip
dependency_groups =
    lint
commands =
    ruff check --fix-only
    ruff format

[testenv:type]
dependency_groups =
    type
    test
commands =
    mypy {posargs}

[testenv:test-django{42,51,52}]
pass_env =
    MINIO_STORAGE_ENDPOINT
    MINIO_STORAGE_ACCESS_KEY
    MINIO_STORAGE_SECRET_KEY
    MINIO_STORAGE_MEDIA_BUCKET_NAME
dependency_groups =
    test
deps =
    django42: Django==4.2.*
    django51: Django==5.1.*
    django52: Django==5.2.*
commands =
    pytest {posargs}
