# Generated by Django 6.1 on 2026-09-16 19:27

from __future__ import annotations

from django.db import migrations, models

import s3_file_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("s3ff_dev", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="s3ff_disabled_blob",
            field=s3_file_field.fields.S3FileField(blank=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="s3ff_disabled_existing_blob",
            field=s3_file_field.fields.S3FileField(default="seed/example.txt"),
        ),
    ]
