# Generated by Django 6.1.1 on 2026-09-29 21:54

from __future__ import annotations

from django.db import migrations

import s3_file_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("s3ff_dev", "0002_resource_s3ff_disabled_blob_alter_resource_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="s3ff_optional_limited_blob",
            field=s3_file_field.fields.S3FileField(blank=True),
        ),
    ]
