services:
  seaweedfs:
    image: chrislusf/seaweedfs:4.48
    environment:
      AWS_ACCESS_KEY_ID: seaweedAccessKey
      AWS_SECRET_ACCESS_KEY: seaweedSecretKey
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8333/healthz"]
      start_period: 30s
      start_interval: 2s
    ports:
      - 8333:8333
      - 23646:23646
