SECRET_KEY = 'test'
AWS_STORAGE_BUCKET_NAME = 't'
AWS_REGION = 't'
AWS_ACCESS_KEY_ID = 't'
AWS_SECRET_ACCESS_KEY = 't'
UPLOAD_STS_ARN = 't'
S3_WIDGET_UPLOAD_DURATION = 3600
AWS_STORAGE_BUCKET_NAME = 't'
