from datetime import datetime
from typing import Any, Mapping, Optional

class Object:
    @property
    def bucket_name(self) -> str: ...
    @property
    def object_name(self) -> str: ...
    @property
    def is_dir(self) -> bool: ...
    @property
    def last_modified(self) -> Optional[datetime]: ...
    @property
    def etag(self) -> Optional[str]: ...
    @property
    def size(self) -> Optional[int]: ...
    @property
    def metadata(self) -> Optional[Mapping[str, Any]]: ...
    @property
    def version_id(self) -> Optional[str]: ...
    @property
    def is_latest(self) -> Optional[bool]: ...
    @property
    def storage_class(self) -> Optional[str]: ...
    @property
    def owner_id(self) -> Optional[str]: ...
    @property
    def owner_name(self) -> Optional[str]: ...
    @property
    def is_delete_marker(self) -> bool: ...
    @property
    def content_type(self) -> Optional[str]: ...
