from urllib3 import HTTPResponse

class MinioException(Exception): ...

class S3Error(MinioException):
    @property
    def code(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def response(self) -> HTTPResponse: ...
