name: ci
on:
  pull_request:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    services:
      seaweedfs:
        image: chrislusf/seaweedfs:4.48
        env:
          AWS_ACCESS_KEY_ID: seaweedAccessKey
          AWS_SECRET_ACCESS_KEY: seaweedSecretKey
        options: >-
          --health-cmd "curl --fail --silent http://localhost:8333/healthz"
          --health-start-period 30s
          --health-start-interval 2s
        ports:
          - 8333:8333
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # Tags are needed to compute the current version number
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ./javascript-client/.node-version
      - name: Run tests
        env:
          MINIO_STORAGE_ENDPOINT: "localhost:8333"
          MINIO_STORAGE_ACCESS_KEY: seaweedAccessKey
          MINIO_STORAGE_SECRET_KEY: seaweedSecretKey
          MINIO_STORAGE_MEDIA_BUCKET_NAME: s3ff-test
        run: |
          uv run --locked tox
  test-javascript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ./javascript-client/.node-version
      - name: Build and test Javascript client
        working-directory: ./javascript-client
        run: |
          npm ci
          npm run build
          npm run test
      - name: Build and test widget
        working-directory: ./widget
        run: |
          npm ci
          npm run build
          npm run test
