name: ci
on:
  pull_request:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    services:
      minio:
        # This image does not require any command arguments (which GitHub Actions don't support)
        image: bitnamilegacy/minio:latest
        env:
          MINIO_ROOT_USER: minioAccessKey
          MINIO_ROOT_PASSWORD: minioSecretKey
        options: >-
          --health-cmd "mc ready local"
          --health-timeout 1s
          --health-start-period 30s
          --health-start-interval 2s
        ports:
          - 9000:9000
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # Tags are needed to compute the current version number
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        env:
          MINIO_STORAGE_ENDPOINT: "localhost:9000"
          MINIO_STORAGE_ACCESS_KEY: minioAccessKey
          MINIO_STORAGE_SECRET_KEY: minioSecretKey
          MINIO_STORAGE_MEDIA_BUCKET_NAME: s3ff-test
        run: |
          uv run --locked tox
  test-javascript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: current
      - name: Build and test Javascript client
        working-directory: ./javascript-client
        run: |
          npm ci
          npm run build
          npm run test
      - name: Build and test widget
        working-directory: ./widget
        run: |
          npm ci
          npm run build
          npm run test
